### PR TITLE
Added additional information to exceptions

### LINKED ISSUE #126: Add processor (?and row?) information to exception object
Would it be possible to add the index (relative to the top level Flow) and name of the flow that failed when an exception is thrown in dataflows? I'm imagining something that intercepts every exception that comes out of running each flow, adds the relevant information either to the stack trace or the exception object, and then raises it again.

This is especially useful if you have multiple load steps and don't know which one is failing. An easy workaround would be to run them one at a time but this would make it a bit easier to work with :)

One step further would also be to find out which row # triggered an error. Obviously wouldn't be relevant for some processors, but for those that do manipulate at a row level it would be a significant help in debugging a failing dataflow.

### PR DESCRIPTION
**Pull request by roll**
- fixes #126

### CODE REVIEW

**Comment by roll** [comment]
Hi @akariv @cschloer,

I played a little bit with additional information on exceptions. It partially works but I don't fully understand how flows are composed so this implementation is really limited.

Can be a starting point for a better implementation

**Comment by cschloer** [comment]
This looks good, and pretty much exactly what I was getting at, but I see that it's only limited to processors that inherit the DataStreamProcessor class. Is there any way to extrapolate this out to the flow.py file? So it works by default for all processors, even custom ones that don't inherit any datahq code? I also am not familiar enough with how flows work to get a sense of whether that is possible.

**Comment by roll** [comment]
hi @akariv WDYT?

**Comment by roll** [comment]
As decided on the prev meeting - it's parked for now to get @akariv input first

**Comment by akariv** [comment]
@roll - sorry for missing this, it's really great!

Regarding the implementation -
- The added information to the exceptions is neat, but most users won't notice them.
   I wonder if we could create a 'DataflowsException' which will have these attributes and will be chained to the original exception (using the `raise ... from e` syntax)
- Flow composition can be done using chaining processors or Flows. 
  The stored position is the processor in the flow, but it might get confusing when combining a number of flows together.
  Perhaps we could have the position to be a combination of Flow + position in flow, but for now I think the implementation is fine.
- row_processor, rows_processor, datapackage_processor, iterable_loader - all return an instance of `DataStreamProcessor` so all should get the position parameter as well

**Comment by roll** [comment]
Hi @akariv,

I've added the exception objects you mentioned. Also, updated the implementation to make it work with different combinations of processors. TBH not sure how it works but it seems to do

**Pull request merged**
