### PR TITLE
Added resources generated by tests to gitignore

### LINKED ISSUE #98: Local test runs create many files not present in codebase or gitignore
# Overview

After `py.test` we end up with a lot neither checked-in nor ignored files.

### PR DESCRIPTION
**Pull request by roll**
- fixes #98

### CODE REVIEW

**Comment by roll** [comment]
@akariv 
Please take a look

**Comment by akariv** [comment]
Would be good to move all outputs to `out/` instead of keeping them in root / data, no?

**Comment by roll** [comment]
@akariv 
I agree. I'll update. I wasn't sure why it uses the current way

**Comment by roll** [comment]
@akariv 
I've updated the tests. So now only one thing I had to add to `.gitignore` is `.checkpoints/`

**Comment by akariv** [comment]
Thanks @roll !!

**Pull request merged**
