### PR TITLE
[WIP] Added collect_errors processor

### LINKED ISSUE #142: An ability to add goodtables checks to the validate processor
# Overview

From `goodtabes@3` (no early alpha) it will have a function like `system.create_check('baseline/integrity/etc')` returning a check object with `check.validate_headers/row/table` available. The amount of checks have been drastically reduces (only 2 core checks and 6 advanced).

So we will be able to integrate it into the `validate` processor like (maybe adding core checks baseline/integrity by default):

```python
Flow(
    validate(extra_checks=['baseline', 'integrity', ('blacklisted-value', {'fieldName': 'name'}), ...]
)
```

As an output, I think we just can add the `errors` list to a resource descriptor with a list of found errors.

Initially `dataflows-goodtables` integration is a @cschloer's idea but, for now, I don't see how we can friend them due to their streaming-nature without going to lower-level (the level of the individual check).

### PR DESCRIPTION
**Pull request by roll**
- fixes #142 

---

Hi @cschloer, 

I've checked options for `goodtables` integration and it doesn't seem doable till the end of this stage. So I dove into the initial issue - https://github.com/BCODMO/laminar_web/issues/801 - and tried to implement something simpler. For example, we can have a `collect_errors` processor that works like this:

```
def test_collect_errors():
    from dataflows import load, collect_errors, Flow
    res, dp, stats = Flow(
        load('data/cities.csv', name='cities'),
        # it accepts an "Extra Schema" that can be partial
        collect_errors({'fields': [{'name': 'city', 'constraints': {'maxLength': 4}}]}),
    ).results()
    assert dp.get_resource('cities').descriptor.get('errors') == [
        'Field "city" has constraint "maxLength" which is not satisfied for value "london"',
        'Field "city" has constraint "maxLength" which is not satisfied for value "paris"'
    ]
```

On the other hand, all the checks @adyork had asked can be set in the main `schema` e.g. using `constraints.pattern` - then the validation will fails in dataflows without this processor.

### CODE REVIEW

**Comment by adyork** [comment]
Thanks for looking into this @roll.  I'm not sure this can get us to the usecase we laid out in https://github.com/BCODMO/laminar_web/issues/801 since it seems to be able to check values of fields, but not the field names.

For example, in your above example it says: 
>  collect_errors({'fields': [{'name': 'city', 'constraints': {'maxLength': 4}}]})
>  'Field "city" has constraint "maxLength" which is not satisfied for value "london"'

But we are looking for something that can check the field name itself ('city' in your example) for constraints: like only [_0-9A-Za-z] allowed, and does not begin with a number. 

As for maybe using the constraints.pattern in schema, I think that has the same problem of looking at the values not the field names? e.g. https://specs.frictionlessdata.io/table-schema/#constraints  is there somewhere else in the documentation I should be looking for that?

Let me know if I am missing something here.

**Comment by roll** [comment]
Oh I see now - what if we just a create a processor that validate a field against JSON Schema?

**Comment by roll** [comment]
cc @cschloer, WDYT?

**Comment by lwinfree** [comment]
@adyork, hey! @roll and I were talking a bit about this today. Would Evgeny's solution (https://github.com/datahq/dataflows/pull/144#issuecomment-669311044) work for the use case?

**Comment by akariv** [comment]
@roll - why not use the `onerror` for `set_type` or `validate`? it seems to accomplish the same purpose, no?

**Comment by roll** [comment]
I think we need a declarative way but this PR is not we need anyway so I'm closing. Thanks

**Pull request closed without merging**
