### PR TITLE
Adds noop processor.

### PR DESCRIPTION
**Pull request by pwalsh**
Useful for composing flows as parameterized higher order functions.

Simple example:

```
import data flows as DF


my_data = [...]

def my_great_flow(validate=False):
    return DF.Flow(
        my_data,
        DF.validate() if validate is True else DF.noop()            
    )
```

An alternative approach would be to allow None values in the processor list passed to a flow (`... else None` rather than `... else DF.noop()`), and then filter the list for Nones before running the processors. I don't have a personal preference but perhaps exposing a noop processor is the more explicit approach for consumers of the library.

### CODE REVIEW

**Comment by akariv** [comment]
Hey @pwalsh, you can actually use None instead of the noop and it will work
as intended.

**Comment by pwalsh** [comment]
:). Don't know how I missed that.

**Comment by akariv** [comment]
Just a testament to the quality of my documentation I guess 😇

**Comment by pwalsh** [comment]
@akariv no, in this case I think early on I had a failing Flow, and thought it was a None processor, so I wrote a noop and moved on, and just kept using it. I never went back to check thoroughly.

**Pull request closed without merging**
