### PR TITLE
Add a new parameter to duplicate to aid join

### PR DESCRIPTION
**Pull request by cschloer**
Hey, currently duplicate automatically adds the new resource directly after the source resource. It would be very useful to have the ability to "duplicate to end", so that we can use the duplicate processor to facilitate joining "out of order" resources. 

long story short: We have a usecase where we want to join resource A with resource B, but resource B came out of resource A and so it is ALWAYS located after resource A. We could load in resource A again, but there are quite a few processing steps that would be duplicated in that case. Using `duplicate` on resource A would work if the duplicated resource ended up after resource B, which this PR would facilitate.

I can make a PR in datapackage_pipelines after this has been accepted in order to make this parameter work properly there as well.

@akariv 
@roll

### CODE REVIEW

**Comment by cschloer** [comment]
Also FYI, it seems as if in the last commit you imported ExcelXMLParser but didn't actually create the file, so none of the checks will pass (though after removing the imports the tests run properly).

**Comment by akariv** [comment]
Thanks @cschloer !

This  looks good - only thing missing is adding documentation for this new parameter in `PROCESSORS.md`.

I've also fixed the tests on master (thanks again) so after rebase the PR should also pass.

**Comment by cschloer** [comment]
OK, updated the documentation and merged in the updates from upstream.

**Comment by akariv** [comment]
Hey @cschloer - thanks! There are still a few lint errors in the code (probably related to a new rule I've added recently to enforce quote style throughout the code). Either way it should take 2 minutes to fix (see here: https://travis-ci.org/github/datahq/dataflows/jobs/766186356)

**Comment by cschloer** [comment]
OK fixed that! @akariv

**Comment by roll** [comment]
Thanks @akariv @cschloer!

**Comment by akariv** [comment]
https://pypi.org/project/dataflows/0.2.11/

**Pull request merged**
